#8.16.0.211
spring:
  datasource:
    url: jdbc:mysql://47.241.98.142:3306/easy_abroad?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: qwer1234
    dynamic:
      datasource:
        master:
          username: root
          password: qwer1234
          url: jdbc:mysql://47.241.98.142:3306/easy_abroad?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
        slave:
          username: root
          password: qwer1234
          url: jdbc:mysql://47.241.98.142:3306/easy_abroad?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      hikari:
        max-lifetime: 120000
  jpa:
    show-sql: false
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
  mail:
    username: lomtom@qq.com
    password: snfbimzpogveebag
    host: smtp.qq.com
    properties:
      mail.smtp.ssl.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.required: true
  redis:
    database: 0
    timeout: 10000
    host: 47.241.98.142
    password: 123456
  elasticsearch:
    rest:
      uris: http://47.241.98.142:9200

canal:
  client:
    instances:
      example:
        host: 47.241.98.142
        port: 11111
        userName: root
        password: 123456


