name: 'tl-covid-report-action'

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Entry CCSU ID'
      home:
        description: 'Location'
        required: false
        default: 'Changsha City'
  schedule:
    - cron: '0 0 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    environment:
        name: gh-ubuntulatest
    steps:
      - name: 'Get Detail'
        run: curl -XPOST -d "${{ secrets.COVID_REPORT_TL_GETQUERY }}" ${{ secrets.COVID_REPORT_URL }}getDetail
      - name: 'Submit Report'
        run: curl -XPOST -d "${{ secrets.COVID_REPORT_TL_SUBMITQUERY }}" ${{ secrets.COVID_REPORT_URL }}doDetail
